---
- name: Validate Network State
  hosts: "{{ target_hosts }}"
  connection: httpapi
  gather_facts: false

  tasks:

    - name: validate states on EOS devices
      ansible.builtin.import_role:
        name: arista.anta_runner
      # vars:
      #   avd_catalogs_filters:
      #     - skip_tests: [VerifyMemoryUtilization, VerifyLoggingErrors]
      #   anta_report_hide_statuses: [success, skipped]
